"""Add classification to companies

Revision ID: 170ab4005aea
Revises: f4a19fd44037
Create Date: 2025-12-05 22:59:08.211194

"""
from alembic import op
import sqlalchemy as sa

import pgvector  # Ensure pgvector is available in migrations

# revision identifiers, used by Alembic.
revision = '170ab4005aea'
down_revision = 'f4a19fd44037'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure vector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('classification', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_classification'), 'companies', ['classification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_classification'), table_name='companies')
    op.drop_column('companies', 'classification')
    # ### end Alembic commands ###
