"""Add missing job fields

Revision ID: 62b7b898edba
Revises: 170ab4005aea
Create Date: 2025-12-08 17:17:51.130141

"""
from alembic import op
import sqlalchemy as sa

import pgvector  # Ensure pgvector is available in migrations

# revision identifiers, used by Alembic.
revision = '62b7b898edba'
down_revision = '170ab4005aea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure vector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('remote_flag', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('seniority', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('ai_forward', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('opp_athena_view', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('opp_role_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('opp_buyer_or_seller', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('opp_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'opp_confidence')
    op.drop_column('jobs', 'opp_buyer_or_seller')
    op.drop_column('jobs', 'opp_role_type')
    op.drop_column('jobs', 'opp_athena_view')
    op.drop_column('jobs', 'ai_forward')
    op.drop_column('jobs', 'seniority')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'remote_flag')
    # ### end Alembic commands ###
