"""add company industry

Revision ID: 6aaf5ea2e8bd
Revises: 62b7b898edba
Create Date: 2025-12-08 19:14:15.151659

"""
from alembic import op
import sqlalchemy as sa

import pgvector  # Ensure pgvector is available in migrations

# revision identifiers, used by Alembic.
revision = '6aaf5ea2e8bd'
down_revision = '62b7b898edba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure vector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
