"""add job role_tier

Revision ID: eac39ace7109
Revises: 6aaf5ea2e8bd
Create Date: 2025-12-08 19:15:56.974952

"""
from alembic import op
import sqlalchemy as sa

import pgvector  # Ensure pgvector is available in migrations

# revision identifiers, used by Alembic.
revision = 'eac39ace7109'
down_revision = '6aaf5ea2e8bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure vector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('role_tier', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_role_tier'), 'jobs', ['role_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_role_tier'), table_name='jobs')
    op.drop_column('jobs', 'role_tier')
    # ### end Alembic commands ###
